apiVersion: v1
kind: Service
metadata:
  name: blaise-server
  namespace: pascalcoin
spec:
  type: ClusterIP
  ports:
  - port: 4003
    targetPort: 4003
    name: api
  selector:
    app: blaise-server